#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
VISUALVM=/Applications/VisualVM.app/Contents
if [ ! -e $DIR/catalina-jmx-remote.jar ] ; then
    scp  vpro05ap@upload-testsites.omroep.nl:/local/tomcat/lib/catalina-jmx-remote.jar $DIR
fi
echo This is possible too, this script is not needed any more then:
echo cp $DIR/catalina-jmx-remote.jar $VISUALVM/platform/lib/


if grep -q -i pomz4aas /etc/hosts ; then
   echo Set in /etc/hosts
   echo 127.0.0.1  ddu19aas ddu17aas pomz4aas pomz7aas pomz9aas ddu17aas poms4aas
fi



echo for dev
echo please tunnel and connect to service:jmx:rmi://pomz4aas:48113/jndi/rmi://pomz4aas:38113/jmxrmi
echo LocalForward 48113 pomz4aas:48113
echo LocalForward 38113 pomz4aas:38113

echo for prod
echo please tunnel and connect to service:jmx:rmi://localhost:2051/jndi/rmi://localhost:2050/jmxrmi
echo LocalForward 2050 poms4aas:2050
echo LocalForward 2051 poms4aas:2051

echo for test
echo please tunnel and connect to service:jmx:rmi://localhost:2053/jndi/rmi://localhost:2052/jmxrmi
echo LocalForward 2052 poms4aas:2052
echo LocalForward 2053 poms4aas:2053


echo please tunnel and connect to service:jmx:rmi://localhost:8687/jndi/rmi://localhost:8686/jmxrmi, also may ddu17aas to localhost in /etc/hosts
echo LocalForward 8686 ddu17aas:8686
echo LocalForward 8687 ddu17aas:8687

echo "Ensure you got the catalina-jmx-remote.jar file"
echo "Copy the uri above into VisualVM jmx."
echo "Password for [admin] user can be found in jmxpasswords file on the upload server (home folder of poms-test)"

$VISUALVM/MacOS/visualvm  -J-Djava.util.logging.config.file=$DIR/logging.properties -J-Djava.net.preferIPv4Stack=true -cp:a $DIR/catalina-jmx-remote.jar &
